# docker-Specify the compose version
version: "3"

services:
  app:
    #Build a Dockerfile in the same directory
    build: .
    #Give the container a name(Any)
    #container_name: 
    #You can keep the container running.
    tty: true
    #Mount the files in the directory to the app directory in the container
    volumes: 
      - ./input:/tmp/emnlp2017/input
      - ./input.example:/tmp/emnlp2017/input.example
      - ./output:/tmp/emnlp2017/output
      - ./checkpoints:/tmp/emnlp2017/checkpoints
      - ./scratchgan/:/tmp/emnlp2017/scratchgan
    #Mount port 1000 on the container side to port 8080 on the host side.
    #ports:
    #  - "8080:8080"
    #command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]